### ISSUE TITLE
[BUG] - Disconnect overlay incorrectly showing error overlay

### ISSUE THREAD

**Issue by dan-tw** [EpicGames/PixelStreamingInfrastructure#176]
**UE Version:**
N/A

**Frontend Version:**
UE5.4 (likely effects multiple versions)

**Problem component**
Frontend

**Description**
If you take a look at

https://github.com/EpicGamesExt/PixelStreamingInfrastructure/blob/0524416fea42ab00d0bfbd04fcb547e6c895ac50/Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts#L243

The outcome of the boolean for the second argument is what decides whether or not a click to reconnect overlay should be displayed or an error overlay.

As a result of this logic, an 'error overlay' will be triggered on anything other than a 1001 close code. 1000 is a normal closure and should not result in an error overlay.

It also appears that the boolean to reconnect is tightly coupled with `MaxReconnectAttempts` which IMO should not be the case, as I would expect that to relate only to automatic reconnects. (Setting this flag to 0 should effectively disable automatic reconnects but not impact a users ability to manually click to restart the stream).

For our use case, we wanted the user to *always* be able to reconnect the stream (even if there was an abnormal closure code). And we also found a grammar error in the AFK text which we were able to fix at the same time.

```js
// override the _onDisconnect function to intercept webrtc disconnect events
// and modify how the event is fired by always showing a click to reconnect overlay.
// we also add a full stop to the AFK message.
stream._onDisconnect = function (eventString: string) {

	// check if the eventString coming in is the inactivity string and add a full stop
	if (eventString == "You have been disconnected due to inactivity") {
		eventString += "."
	}

	this._eventEmitter.dispatchEvent(
		new WebRtcDisconnectedEvent({
			eventString: eventString,
			allowClickToReconnect: true
		})
	);
}
```

**Platform (please complete the following information):**
 - OS: Ubuntu Linux 22.04 LTS
 - Chrome 126.0.6478.126 (Official Build) (64-bit)

**Comment by mcottontensor** [comment]
It seems here that the issue is mostly the naming of the overlay? Because that boolean only controls if we show the 'DisconnectOverlay' or the 'ErrorOverlay' and the only real difference between them is that one listens for clicks (the disconnect overlay) and the other just displays a message (the error overlay).

The only time we display the disconnect overlay (and thus allowing the user to click to reconnect) is if the frontend isn't automatically attempting a reconnection itself.

I'm curious to know what conditions have the frontend disconnecting without an auto reconnect AND without the user being able to click to reconnect.
