### ISSUE TITLE
[BUG] UE5.4-1.1.2(.tar.gz/.zip) contain wrong content

### ISSUE THREAD

**Issue by PhDittmann** [EpicGames/PixelStreamingInfrastructure#211]
**UE Version:**
UE 5.4

**Frontend Version:**
UE5.4-1.1.2

**Problem component**
Whole source code

**Description**
Using `Engine/Plugins/Media/PixelStreaming/Resources/WebServers/get_ps_servers.(bat|sh)` reconfigured to [EpicGamesExt/PixelStreamingInfrastructure](https://github.com/EpicGamesExt/PixelStreamingInfrastructure) in UE5.4.x tags leads to the archives [UE5.4-1.1.2.tar.gz](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/releases/download/UE5.4-1.1.2/UE5.4-1.1.2.tar.gz) and [UE5.4-1.1.2.zip](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/releases/download/UE5.4-1.1.2/UE5.4-1.1.2.zip) in [Releases/UE5.4-1.1.2](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/releases/tag/UE5.4-1.1.2), which contain outdated code, most probably [UE5.4-1.0.0](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/tree/UE5.4-1.0.0). The 'Source code' archives are fine.

**Steps to Reproduce:**
1. Clone UE 5.4.x
2. 
```shell
cd Engine/Plugins/Media/PixelStreaming/Resources/WebServers/
#./get_ps_servers.bat # Windows
./get_ps_servers.sh # Linux
```
or download [UE5.4-1.1.2.tar.gz](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/releases/download/UE5.4-1.1.2/UE5.4-1.1.2.tar.gz) or [UE5.4-1.1.2.zip](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/releases/download/UE5.4-1.1.2/UE5.4-1.1.2.zip) directly and compare with [UE5.4-1.1.2](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/tree/UE5.4-1.1.2) and [UE5.4-1.0.0...1.0.1](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/compare/UE5.4-1.0.0...UE5.4-1.0.1).
* Missing folders: i.e. Common, SS_Test, Signalling.
* Outdated CHANGELOG.md

**Expected behavior**
1. I'd expect UE5.4-1.1.2.tar.gz and UE5.4-1.1.2.zip to be build versions of tags/UE5.4-1.1.2.tar.gz and tags/UE5.4-1.1.2.zip.

**Screenshots**
![UE5 4 x_PS_Differs](https://github.com/user-attachments/assets/ee30b0f3-80be-4be1-b03f-98f3159134d2)

**Platform:**
 - OS: all
 - Browser: independent
 - Version: all

**Comment by lukehb** [comment]
Hi @PhDittmann,

Good catch!

This was actually impacting all our releases and tags it turns out.

The fix to our workflow is here: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/commit/96980c2225b1b4bc612a7d28c1aefffc59eec118#diff-370235e4175e2c8cac03f0508bf0803c83cd736ec8e2e22eab4ef486c8139bf7R85

Basically, our Github Action was using the latest commit from `master` branch always, even if we were making a release for another branch, say `UE5.4`.

I have gone through this repo and corrected all the old tags and releases to match their proper commit and have the proper source code in them. I can't do this for the old PSInfra repo though as it is archived.

One thing I will correct (that you will now see in the releases too), if you are using a 5.4 release you won't see the directories

> Missing folders: i.e. Common, SS_Test, Signalling.

The reason being is that these directories were added new in the `5.5` branch. The reason you see them in `master` is that the  `master` branch is tracking `5.5` now that `5.4` has shipped. If you want to work using those new components, you will need to use the `5.5` releases.

**Comment by PhDittmann** [comment]
Hi @lukehb,

thanks for the quick fix! I don't use the new components, but for identifying, that the build archives differ the source archives.
