### ISSUE TITLE
Import Old Resolved Issues Here To Preserve Legacy

### ISSUE THREAD

**Issue by TxMat** [EpicGames/PixelStreamingInfrastructure#22]
**Component your feature request relates to**
+ This repo

**Problem your feature solves? Please describe.**
Moving the repo was announced but it'll be nice to import the old resolved issues to as they were very helpful, (like that one issue to fix the memory leak in UE5.3)

**Describe the solution you'd like**
import relevant closed issues as well if possible.

**Comment by timbotimbo** [comment]
Looks like the contents of those closed issues are fully erased from the web.
- The old repo doesn't have an issue tab anymore.
- [The wayback machine](https://web.archive.org/web/*/https://github.com/EpicGames/PixelStreamingInfrastructure/*) has only captured the contents of 3 issues

I've seen archived repos that have retained their issues, so that is possible.  
Keeping a locked list of the old issues on the old repo could be a possible middle ground.

**Comment by lukehb** [comment]
I can't import them, but I have restored them on the archived repo. 

https://github.com/EpicGames/PixelStreamingInfrastructure/issues?q=is%3Aissue+is%3Aclosed

Closing this one.
