### ISSUE TITLE
Network Requirement for the Host

### ISSUE THREAD

**Issue by shrenik2703** [EpicGames/PixelStreamingInfrastructure#265]
Dear Team,

We would like to inquire about the minimum network bandwidth and speed required for a machine running an Unreal Engine application instance _(not the one viewing the application on a browser)_. Could you please provide your recommendation on the optimal network specifications for ensuring smooth performance on the host machine?

Thank you for your assistance.

**Comment by mcottontensor** [comment]
This depends entirely on the configuration of the stream. The streamer is designed to scale with available bandwidth in various ways such as lower quality encoding, resolution scaling or framerate limiting. It also depends on the complexity of the scenes being streamed.

Since we use H264, VP8 or VP9 your best bet is to look up recommended bit rates of these codecs for the configuration you're wanting to use. However as a very rough guide, we look at 5 to 20 mbps for a decent quality stream.
