### ISSUE TITLE
NPM package releases

### ISSUE THREAD

**Issue by DenisTensorWorks** [EpicGames/PixelStreamingInfrastructure#5]
First we need to complete the following tasks:

- [x] https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/1
- [ ] https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/2

Once we have done this, we can further improve the user experience in using `PixelStreamingInfrastructure` by synthesising it's libraries into a single or multiple semantically versioned npm packages, generating these automatically as new changes make their way into this repository.

---

Moved from https://github.com/EpicGames/PixelStreamingInfrastructure/issues/14

**Comment by lukehb** [comment]
Close as it is effectively duplicated by: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/2

**Comment by DreamerYinYu** [comment]
Hello, I don't think the pixel streaming npm package for UE5.1 has been released, has it? What about UE5.1? thank you

**Comment by lukehb** [comment]
@DreamerYinYu As I recall, 5.2 is the first version where the infrastructure was not shipped with the release of UE itself and therefore needed an NPM package. For 5.1, there is no NPM package because it was just a loose collection of js files with no real API to build on top of. For versions like 5.1 or older you should see the official UE docs tell you where to find the frontend and signalling server files - as I recall it was in like samples/pixelstreaming.
